export interface NotificationOption {
    readonly type?: NotificationType;
    enabled?: boolean | null;
}

export enum NotificationType {
    ACTIVITY_MESSAGE = 'ACTIVITY_MESSAGE',
    ACTIVITY_REPLY = 'ACTIVITY_REPLY',
    FOLLOWING = 'FOLLOWING',
    ACTIVITY_MENTION = 'ACTIVITY_MENTION',
    THREAD_COMMENT_MENTION = 'THREAD_COMMENT_MENTION',
    THREAD_SUBSCRIBED = 'THREAD_SUBSCRIBED',
    THREAD_COMMENT_REPLY = 'THREAD_COMMENT_REPLY',
    AIRING = 'AIRING',
    ACTIVITY_LIKE = 'ACTIVITY_LIKE',
    ACTIVITY_REPLY_LIKE = 'ACTIVITY_REPLY_LIKE',
    THREAD_LIKE = 'THREAD_LIKE',
    THREAD_COMMENT_LIKE = 'THREAD_COMMENT_LIKE',
    ACTIVITY_REPLY_SUBSCRIBED = 'ACTIVITY_REPLY_SUBSCRIBED',
    RELATED_MEDIA_ADDITION = 'RELATED_MEDIA_ADDITION',
    MEDIA_DATA_CHANGE = 'MEDIA_DATA_CHANGE',
    MEDIA_MERGE = 'MEDIA_MERGE',
    MEDIA_DELETION = 'MEDIA_DELETION'
}
