query($page: Int, $id: Int, $search: String) {
    Page(page: $page, perPage: 1) {
        pageInfo {
            total
            perPage
            currentPage
            lastPage
            hasNextPage
        }
        studios(id: $id, search: $search) {
            id
            name
            isAnimationStudio
            media {
                pageInfo {
                    total
                    perPage
                    currentPage
                    lastPage
                    hasNextPage
                }
            }
            siteUrl
            favourites
        }
    }
}
