query($page: Int, $id: Int, $search: String) {
    Page(page: $page, perPage: 1) {
        pageInfo {
            currentPage
            total
            lastPage
            hasNextPage
        }
        users(id: $id, search: $search) {
            id
            name
            avatar {
                large
                medium
            }
            bannerImage
            options {
                titleLanguage
                displayAdultContent
                airingNotifications
                profileColor
                timezone
                activityMergeTime
                staffNameLanguage
            }
            mediaListOptions {
                scoreFormat
                rowOrder
                useLegacyLists
                sharedTheme
                sharedThemeEnabled
            }
            favourites {
                anime {
                    pageInfo {
                        total
                        perPage
                        currentPage
                        lastPage
                        hasNextPage
                    }
                }
                manga {
                    pageInfo {
                        total
                        perPage
                        currentPage
                        lastPage
                        hasNextPage
                    }
                }
                characters {
                    pageInfo {
                        total
                        perPage
                        currentPage
                        lastPage
                        hasNextPage
                    }
                }
                staff {
                    pageInfo {
                        total
                        perPage
                        currentPage
                        lastPage
                        hasNextPage
                    }
                }
                studios {
                    pageInfo {
                        total
                        perPage
                        currentPage
                        lastPage
                        hasNextPage
                    }
                }
            }
            statistics {
                anime {
                    count
                    meanScore
                    standardDeviation
                    minutesWatched
                    chaptersRead
                    volumesRead
                    formats {
                        count
                        format
                    }
                    statuses {
                        count
                        status
                    }
                    scores {
                        count
                        score
                    }
                    lengths {
                        count
                        length
                    }
                    releaseYears {
                        count
                        releaseYear
                    }
                    startYears {
                        count
                        startYear
                    }
                    genres {
                        count
                        genre
                    }
                    tags {
                        count
                        tag {
                            id
                        }
                    }
                    countries {
                        count
                        country
                    }
                    voiceActors {
                        count
                        voiceActor {
                            id
                        }
                    }
                    staff {
                        count
                        staff {
                            id
                        }
                    }
                    studios {
                        count
                        studio {
                            id
                        }
                    }
                }
                manga  {
                    count
                    meanScore
                    standardDeviation
                    minutesWatched
                    chaptersRead
                    volumesRead
                    formats {
                        count
                        format
                    }
                    statuses {
                        count
                        status
                    }
                    scores {
                        count
                        score
                    }
                    lengths {
                        count
                        length
                    }
                    releaseYears {
                        count
                        releaseYear
                    }
                    startYears {
                        count
                        startYear
                    }
                    genres {
                        count
                        genre
                    }
                    tags {
                        count
                        tag {
                            id
                        }
                    }
                    countries {
                        count
                        country
                    }
                    voiceActors {
                        count
                        voiceActor {
                            id
                        }
                    }
                    staff {
                        count
                        staff {
                            id
                        }
                    }
                    studios {
                        count
                        studio {
                            id
                        }
                    }
                }
            }
            siteUrl
            donatorTier
            donatorBadge
            moderatorRoles
            createdAt
            updatedAt
            previousNames {
                name
                createdAt
                updatedAt
            }
        }
    }
}
