export default interface DonmaiAPIPost {
    readonly id: number,
    readonly created_at: string,
    readonly uploader_id: number,
    readonly score: number,
    readonly source: string,
    readonly md5: string,
    readonly last_comment_bumped_at: string | null,
    readonly rating: string,
    readonly image_width: number,
    readonly image_height: number,
    readonly tag_string: string,
    readonly is_note_locked: boolean,
    readonly fav_count: number,
    readonly file_ext: string,
    readonly last_noted_at: string | null,
    readonly is_rating_locked: boolean,
    readonly parent_id: number | null,
    readonly has_children: boolean,
    readonly approver_id: number,
    readonly tag_count_general: number,
    readonly tag_count_artist: number,
    readonly tag_count_character: number,
    readonly tag_count_copyright: number,
    readonly file_size: number,
    readonly is_status_locked: boolean,
    readonly pool_string: string,
    readonly up_score: number,
    readonly down_score: number,
    readonly is_pending: boolean,
    readonly is_flagged: boolean,
    readonly is_deleted: boolean,
    readonly tag_count: number,
    readonly updated_at: string,
    readonly is_banned: boolean,
    readonly pixiv_id: number,
    readonly last_commented_at: string | null,
    readonly has_active_children: boolean,
    readonly bit_flags: number,
    readonly tag_count_meta: number,
    readonly has_large: boolean,
    readonly has_visible_children: boolean,
    readonly tag_string_general: string,
    readonly tag_string_character: string,
    readonly tag_string_copyright: string,
    readonly tag_string_artist: string,
    readonly tag_string_meta: string,
    readonly file_url: string,
    readonly large_file_url: string,
    readonly preview_file_url: string
}
