query($id: Int, $search: String) {
    User(id: $id, search: $search) {
        id
        name
        avatar {
            large
            medium
        }
        siteUrl
        statistics {
            manga {
                count
                meanScore
                standardDeviation
                chaptersRead
                volumesRead
                formats {
                    format
                    count
                }
                statuses {
                    status
                    count
                }
                scores {
                    score
                    count
                }
                lengths(sort: ID) {
                    length
                    count
                }
                genres(sort: COUNT_DESC) {
                    genre
                    count
                    meanScore
                }
                tags(sort: COUNT_DESC) {
                    tag {
                        id
                        name
                    }
                    meanScore
                    count
                }
            }
        }
    }
}
