query($userId: Int, $mediaId: Int) {
    Page(perPage: 1, page: 0) {
        pageInfo {
            total
            perPage
            currentPage
            lastPage
            hasNextPage
        }
        mediaList(userId: $userId, mediaId: $mediaId) {
            score
            media {
                id
            }
        }
    }
}
